title: Shane Keniley # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Research Assistant, PhD Candidate 
  <br><br>
  University of Illinois at Urbana-Champaign
  <br><br>
  Nuclear, Plasma, and Radiological Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/shanekeniley"">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
